"use client";
import { useEffect, useState } from "react";
import { liveRatingResponses } from "@/data/data";
import type { LiveTour, RatingResponse } from "@/types/live-tour";

export default function RatingsResponseModal({ tour, initialModuleId, onClose }: { tour: LiveTour; initialModuleId?: string; onClose: () => void }) {
  const tourId = tour.id;
  const [allResponses, setAllResponses] = useState<RatingResponse[]>(liveRatingResponses as RatingResponse[]);
  const modulesWithResponses = tour.modules.filter((module) => allResponses.some((response) => response.tourId === tour.id && response.moduleId === module.id));
  const [moduleId, setModuleId] = useState(initialModuleId ?? modulesWithResponses[0]?.id ?? tour.modules[0]?.id ?? "");
  useEffect(() => { fetch(`/api/rating-responses?tourId=${encodeURIComponent(tourId)}`, { cache: "no-store" }).then((response) => response.ok ? response.json() as Promise<RatingResponse[]> : Promise.reject()).then(setAllResponses).catch(() => undefined); }, [tourId]);
  const tripModule = tour.modules.find((item) => item.id === moduleId) ?? tour.modules[0];
  const responses = allResponses.filter((response) => response.tourId === tour.id && response.moduleId === moduleId);
  const average = responses.length ? responses.reduce((sum, response) => sum + response.rating, 0) / responses.length : 0;
  const distribution = [5,4,3,2,1].map((star) => ({ star, count: responses.filter((response) => response.rating === star).length }));
  const tabs = tour.modules;
  if (!tripModule) return <div className="responses-backdrop" onMouseDown={onClose}><section className="responses-modal" role="dialog" aria-modal="true" aria-labelledby="responses-title" onMouseDown={(event) => event.stopPropagation()}><header><div><p className="admin-eyebrow">Module-level traveller feedback</p><h2 id="responses-title">No itinerary modules</h2><p>{tour.title}</p></div><button onClick={onClose} aria-label="Close ratings and responses">×</button></header><p className="empty-state">This tour day does not have any itinerary modules yet.</p><footer><button onClick={onClose}>Done</button></footer></section></div>;
  return <div className="responses-backdrop" onMouseDown={onClose}><section className="responses-modal" role="dialog" aria-modal="true" aria-labelledby="responses-title" onMouseDown={(event) => event.stopPropagation()}><header><div><p className="admin-eyebrow">Module-level traveller feedback</p><h2 id="responses-title">Ratings & responses</h2><p>{tour.title} · {tour.date}</p></div><button onClick={onClose} aria-label="Close ratings and responses">×</button></header><div className="response-module-tabs">{tabs.map((module) => { const count = allResponses.filter((response) => response.tourId === tour.id && response.moduleId === module.id).length; return <button className={module.id === moduleId ? "active" : ""} onClick={() => setModuleId(module.id)} key={module.id}><strong>{module.title}</strong><small>{count} response{count === 1 ? "" : "s"}</small></button>; })}</div><section className="response-summary"><div><span>Selected module rating</span><strong>{responses.length ? `★ ${average.toFixed(1)}` : "—"}</strong><small>{responses.length} of {tour.guests} travellers responded</small></div><div className="response-distribution">{distribution.map((item) => <span key={item.star}><small>{item.star}★</small><i><b style={{ width: `${responses.length ? (item.count / responses.length) * 100 : 0}%` }} /></i><em>{item.count}</em></span>)}</div><div><span>Response rate</span><strong>{Math.round((responses.length / tour.guests) * 100)}%</strong><small>{tripModule.venue}</small></div></section><div className="individual-responses"><div className="responses-heading"><h3>{tripModule.title}</h3><span>Newest first</span></div>{responses.length === 0 && <p className="empty-state">No reviews have been submitted for this part of the tour yet.</p>}{[...responses].reverse().map((response) => <article key={response.id}><div className="response-score"><strong>{response.rating}</strong><span>★</span></div><div className="response-content"><div><strong>{response.anonymous ? "Anonymous traveller" : "Traveller"}</strong><time>{response.submittedAt}</time></div><div className="response-tags">{response.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><p>{response.comment || <em>No written comment</em>}</p></div></article>)}</div><footer><div><span>Module</span><strong>{tripModule.title}</strong></div><button onClick={onClose}>Done</button></footer></section></div>;
}
